name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Tests (token)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install dependencies
        working-directory: token
        run: go get .

      - name: Build
        working-directory: token
        run: go build -v ./...

      - name: Run Tests
        working-directory: token
        run: go test
